//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursProj.Model
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.UserBookPair = new HashSet<UserBookPair>();
        }
    
        public int id { get; set; }
        public string article { get; set; }
        public string name { get; set; }
        public int yearOfPublic { get; set; }
        public string description { get; set; }
        public int authorID { get; set; }
        public int genreID { get; set; }
        public int publishID { get; set; }
        public int stateID { get; set; }
        public string image { get; set; }
        public Nullable<int> currentOwnerID { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Genres Genres { get; set; }
        public virtual PublishingHouse PublishingHouse { get; set; }
        public virtual State State { get; set; }
        public virtual User User { get; set; }

        public string correctimage
        {
            get
            {
                string path = Path.Combine(Directory.GetParent(Path.Combine(Directory.GetParent(Directory.GetCurrentDirectory()).FullName)).FullName, @"Images\");
                if (String.IsNullOrEmpty(image) || String.IsNullOrWhiteSpace(image) || image == null)
                {
                    return path + "booksImage.png";
                }
                else
                {
                    return path + image;
                }
            }
        }

            [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserBookPair> UserBookPair { get; set; }
    }
}
